### ISSUE TITLE
Need[0][0] gets wrong value in 3_Banker\'s-Algo/Bankers.c

### ISSUE THREAD

**Issue by iambk** [iambk/SSlab#1]
#### Description
Need[0][0] alone gets its value wrong.

##### How to reproduce
Try debugging the program by printing value of Need[0][0], you will observe that it gets its value correct for the first time when its calculated, but after that the value is wrong.

PS: I couldn't figure out the reason for this behavior. If anyone can explain why, it would be helpful as well.

**Comment by AceKnight** [comment]
Hey, Can you please explain the Code?

**Comment by iambk** [comment]
@AceKnight It's the C implementation of [Banker's algorithm](https://en.wikipedia.org/wiki/Banker%27s_algorithm)

I guess you need not know all this (it's good if you know). The error happens after line 30, 
Need[i][k] = Max[i][k] - Allocation[i][k] where Max and Allocation are arrays to hold the resources held by each process.

At line 30, the value for Need[i][k] is correct but after that it becomes wrong.

**Comment by YEGNESWAR07** [comment]
def bankers_algorithm(filename):
    with open(filename, 'r') as file:
        lines = file.readlines()

    # Parse the input
    available = list(map(int, lines[0].strip()[1:-1].split()))
    max_resources = [list(map(int, line.strip()[1:-1].split())) for line in lines[1:]]

    # Initialize data structures
    n = len(max_resources) // 2
    m = len(available)
    allocation = max_resources[:n]
    max_need = max_resources[n:]
    need = [[max_need[i][j] - allocation[i][j] for j in range(m)] for i in range(n)]
    finish = [False]*n
    safe_sequence = []

    # Main loop of the Banker's algorithm
    while len(safe_sequence) < n:
        for i in range(n):
            if not finish[i] and all(need[i][j] <= available[j] for j in range(m)):
                available = [available[j] + allocation[i][j] for j in range(m)]
                finish[i] = True
                safe_sequence.append(i)

    # Check if a safe sequence was found
    if len(safe_sequence) < n:
        print("No safe sequence found.")
    else:
        print("Safe sequence: ", end="")
        for i in safe_sequence:
            print(f"P{i}", end=", " if i != safe_sequence[-1] else "\n")

# Test the function
bankers_algorithm('input.txt')
i hope it solves your  problem

**Comment by iambk** [comment]
@YEGNESWAR07 Thanks for checking on this but, I wasn't looking for a python implementation. Also, unfortunately I don't think this repo matters to me anymore so I'm gonna close this issue and archive the repo.
